# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=alderlake -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
#LC_MESSAGES=C.UTF-8

FEATURES="candy news parallel-fetch userfetch userpriv usersandbox"

# Appending getbinpkg to the list of values within the FEATURES variable
FEATURES="${FEATURES} getbinpkg"
# Require signatures
FEATURES="${FEATURES} binpkg-request-signature"

INPUT_DEVICES="libinput evdev"
VIDEO_CARDS="intel"
ALSA_CARDS="hda-intel"

# for app-portage/elogv
PORTAGE_ELOG_SYSTEM="save"
PORTAGE_ELOG_CLASSES="warn error info log qa"

ACCEPT_KEYWORDS="~amd64"

ACCEPT_LICENSE="*"

EMERGE_DEFAULT_OPTS="--autounmask-write y --keep-going y --quiet-build y"

USE="${USE} -libav -pulseaudio alsa bluetooth cjk cups dbus dist-kernel libinput nls udev vim-syntax xinerama"
